[project]
name = "media-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "customtkinter>=5.2.2",
    "instaloader>=4.14.2",
    "pydantic>=2.11.8",
    "pytest>=8.4.2",
    "requests>=2.32.5",
    "tk>=0.1.0",
    "urllib3>=2.5.0",
    "yt-dlp>=2025.9.5",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.9.0",
]

[dependency-groups]
dev = [
    "ruff>=0.13.0",
]
